guiadomilico/apps/accounts/urls.py
from django.conf.urls import url
from django.urls import path

from guiadomilico.apps.accounts.views import login, cadastro

app_name = 'accounts'

urlpatterns = [
    url(r'login/$', login.LoginView.as_view(), name='login'),
    url(r'logout/$', login.LoginView.as_view(), name='logout'),
    path('cadastro/', cadastro.CadastroWizard.as_view(), name='cadastroUsuario'),
    path('my-account/<int:pk>', cadastro.CadastroUpdateView.as_view(), name='my-account'),
    path('confirm/<str:uidb64>/<str:token>', cadastro.ativarCadastro, name='cadastroAtivar'),
    path('cadastro/ativar-conta', cadastro.EmailActiveView.as_view(), name='ativar-conta'),
    path('cadastro/reenviar-email', cadastro.accounts_inactive, name='cadastroReenvioEmail'),
    path('cadastro/ativado', cadastro.ativadoSucesso, name='ativado'),
    url('ajax/is_exists_register_ajax/', cadastro.is_exists_register_ajax, name='is_exists_register_ajax'),
    url('ajax/verifica_cep/', cadastro.consultar_cep, name='verifica_cep'),

]

guiadomilico/apps/base/urls.py
from django.conf.urls import url
from . import views


app_name = 'base'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^loja-virtual/$', views.ShopView.as_view(), name='loja-virtual'),

]

guiadomilico/apps/blog/urls.py
from django.conf.urls import url
from .views import base

app_name = 'blog'
urlpatterns = [
    url(r'^$', base.post_list, name='list'),
    url(r'^post/(?P<pk>[0-9]+)/$', base.post_detail, name='detail'),
    url(r'^post/new/$', base.post_new, name='post_new'),
    url(r'^post/(?P<pk>[0-9]+)/edit/$', base.post_edit, name='post_edit'),
]

guiadomilico/urls.py
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url('admin/', admin.site.urls),
    #URL do app BASE:
    url(r'^', include('guiadomilico.apps.core.urls')),
    url(r'^accounts/', include('guiadomilico.apps.accounts.urls')),
    url(r'^dashboard/', include('guiadomilico.apps.dashboard.urls')),
    url(r'^blog/' , include('guiadomilico.apps.blog.urls')),
]

guiadomilico/apps/dashboard/models/models.py
from django.db import models

# Create your models here.

guiadomilico/apps/blog/forms/base.py
from django import forms

from guiadomilico.apps.blog.models import Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'text']

        labels = {
            'title':'Titulo da postagem',
            'text': 'Digite o conteúdo'
        }

        widgets = {
            'text': forms.Textarea(attrs={'hidden': 'hidden', '':'text'}),
        }

guiadomilico/apps/accounts/views/cadastro.py
from django.contrib.auth import logout, login

from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage, send_mail
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.urls import reverse_lazy, reverse
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views.generic import FormView, TemplateView
from guiadomilico.apps.accounts.forms import EnderecoFormSet, TelefoneFormSet
from guiadomilico.apps.accounts.token import account_activation_token
from guiadomilico.apps.accounts.forms.cadastro import CadastroUserForm, CadastroUpdateForm
from guiadomilico.apps.accounts.models.base import Usuario, Endereco
from formtools.wizard.views import SessionWizardView
from  django.views.generic.edit import UpdateView
from  django.views.generic.list import ListView

import pycep_correios as pycep

from ..models import *

def send_mail(request, usuario):
    current_site = get_current_site(request)
    mail_subject = "[Guia do Milico] Ativação de usuário necessária"
    message = render_to_string('accounts/email_ativacao.html', {
        'usuario': usuario,
        'dominio': current_site.domain,
        'uid': urlsafe_base64_encode(force_bytes(usuario.pk)),
        'token': account_activation_token.make_token(usuario),
    })
    to_email = usuario.email

    email = EmailMessage(
        mail_subject,
        message,
        to=[to_email]
    )

    email.send()


## VIEW EM DESENVOLVIMENTO ##
class CadastroUpdateView(UpdateView):
    template_name = 'accounts/my_account.html'
    model = Usuario
    form_class = CadastroUpdateForm
    context_object_name = "usuario"

    def get_success_url(self):
        id = self.kwargs.get(self.pk_url_kwarg)
        return reverse_lazy('accounts:my-account', kwargs={'pk': id })

    def get_context_data(self, **kwargs):
        id = self.kwargs.get(self.pk_url_kwarg)
        kwargs['usuario'] = Usuario.objects.filter(id=id).first()
        kwargs['usuario_form'] = CadastroUpdateForm(self.request.POST or None, instance=kwargs['usuario'])
        kwargs['endereco'] = list(Endereco.objects.filter(usuario_end__pk=self.kwargs['pk']).values())
        kwargs['TIPO_ENDERECO'] = TIPO_ENDERECO
        return super().get_context_data(**kwargs)



class CadastroListView(ListView):
    template_name = 'accounts/my_account.html'
    model = Usuario
    form_class = CadastroUserForm
    context_object_name = "usuario"


class EnderecoListView(ListView):
    template_name = 'accounts/my_account.html'
    model = Usuario
    form_class = CadastroUserForm
    context_object_name = "usuario"

class CadastroWizard(SessionWizardView):
    template_name = 'accounts/cadastro_usuario.html'

    FORMS = [("usuario", CadastroUserForm),
             ("endereco", EnderecoFormSet),
             ("telefone", TelefoneFormSet)
             ]

    form_list = FORMS


    def done(self, form_list, form_dict, **kwargs):

        template_name = 'accounts/email_notification.html'
        context = {}
        form_data = [form.cleaned_data for form in form_list]
        usuario = CadastroUserForm(form_data[0])
        user = usuario.save(commit=False)
        usuario.is_trusty = False
        instance = usuario.save()

        if 'endereco' in form_dict:
            formset = form_dict['endereco']
            if formset.is_valid():
                formset.instance = instance
                instance_endereco = formset.save()
                usuario.endereco_padrao = instance_endereco


        if 'telefone' in form_dict:
            formset = form_dict['telefone']
            if formset.is_valid():
                formset.instance = instance
                instance_telefone = formset.save()
                usuario.telefone_padrao = instance_telefone

        usuario.save()
        send_mail(self.request, user)

        # Context para avisar ao usuário que o cadastro foi efetuado com sucesso.
        # self.extra_context['form'] = self.get_form_instance(0)

        context['nomeCompleto'] = instance.get_full_name()
        context["emailEnvio"] = instance.email
        context["sucessoCadastro"] = "Um email foi enviado para {} com um link de ativação.".format(instance.email)

        return render(self.request, template_name, context )


'''
class CadastroUserView(FormView):
    form_class = CadastroUserForm
    template_name = 'accounts/cadastro_usuario.html'
    
    extra_context = {}
    endereco = EnderecoFormSet(prefix='endereco')
    telefone = TelefoneFormSet(prefix='telefone')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context["endereco"] = EnderecoFormSet(self.request.POST)
            context["telefone"] = TelefoneFormSet(self.request.POST)

        else:
            context["endereco"] = EnderecoFormSet()
            context["telefone"] = TelefoneFormSet()

        return context

    def get(self, request, *args, **kwargs):

        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        endereco = EnderecoFormSet()
        telefone = TelefoneFormSet()

        return self.render_to_response(
            self.get_context_data(form=form,
                                  endereco=endereco,
                                  telefone=telefone
                                  )
        )

    def post(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        endereco = EnderecoFormSet(self.request.POST)
        telefone = TelefoneFormSet(self.request.POST)

        if form.is_valid() and endereco.is_valid():
            return self.form_valid(form, endereco, telefone)
        else:
            return self.form_invalid(form, endereco, telefone)

    def form_valid(self, form, endereco, telefone):
        usuario = form.save(commit=False)
        usuario.is_trusty = False
        self.object = form.save()
        endereco.instance = self.object
        endereco.save()
        telefone.instance = self.object
        telefone.save()
        send_mail(self.request, usuario)

        # Context para avisar ao usuário que o cadastro foi efetuado com sucesso.
        self.extra_context['form'] = self.form_class

        self.extra_context['nomeCompleto'] = "{} {}".format(usuario.nome, usuario.sobrenome)
        self.request.session["emailEnvio"] = usuario.email
        self.request.session["sucessoCadastro"] = "Um email foi enviado para {} com um link de ativação.".format(
            usuario.email)

        return super(CadastroUserView, self).form_valid(form)

    def form_invalid(self, form, endereco, telefone):

        return self.render_to_response(
            self.get_context_data(form=form,
                                  endereco=endereco,
                                  telefone=telefone
                                  )
        )

'''


def ativadoSucesso(request):
    template_name = 'accounts/active_sucess.html'
    return render(request, template_name)


def ativa(uidb64, token):
    _return = {}
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = Usuario.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, Usuario.DoesNotExist):
        user = None

    if user is not None:
        if account_activation_token.check_token(user, token):
            user.is_trusty = True
            user.save()
        else:
            user = None
            _return['erro'] = 'Token inválido ou já utilizado!'
    else:
        _return['erro'] = 'Usuário inválido!'
    _return['usuario'] = user
    return _return


def ativarCadastro(request, uidb64, token):
    logout(request)

    _return = ativa(uidb64, token)
    if _return['usuario']:
        login(request, _return['usuario'])
        return redirect('accounts:ativado')
    else:
        context = {}
        context['erro'] = _return['erro']
        template_name = 'accounts/login.html'
        return render(request, template_name, context)


class EmailActiveView(TemplateView):
    template_name = 'accounts/email_notification.html'

    def get_context_data(self, **kwargs):
        context = super(EmailActiveView, self).get_context_data(**kwargs)
        context['sucessoCadastro'] = self.request.session["sucessoCadastro"]
        context['emailEnvio'] = self.request.session["emailEnvio"]
        del self.request.session["sucessoCadastro"]
        del self.request.session["emailEnvio"]

        return context


def accounts_inactive(request):
    logout(request)
    template_name = 'accounts/cadastro_inativo.html'
    context = {}

    if request.method == 'POST':
        username = request.POST['username']

        if Usuario.objects.filter(email=username).count() == 1:
            usuario = Usuario.objects.get(email=username)
        elif Usuario.objects.filter(username=username).count() == 1:
            usuario = Usuario.objects.get(username=username)
        else:
            usuario = None

        if usuario is not None:
            send_mail(request, usuario)

            request.session['sucessoCadastro'] = "Um email foi enviado para {} com um link de ativação.".format(
                usuario.email)
            request.session['emailEnvio'] = usuario.email

            return redirect(reverse('accounts:ativar-conta'))

        else:
            context['erro'] = "Nome de usuário/Email não encontrado!"

        return render(request, template_name, context)

    return render(request, template_name, context)


def is_exists_register_ajax(request):
    field = request.GET.get('field', None)
    validate = request.GET.get('validate', None)

    if validate is not None:
        if validate == 'username':

guiadomilico/apps/accounts/views/login.py
from django.contrib.auth import login, logout
from django.core.validators import validate_email

from django.utils.decorators import method_decorator
from django.urls import reverse_lazy

from django.views.decorators.csrf import csrf_protect
from django.views.decorators.cache import never_cache
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import FormView, RedirectView

from django.shortcuts import render

from guiadomilico.apps.accounts.models.base import Usuario
from guiadomilico.apps.accounts.forms.login import LoginForm


# Create your views here.

class LoginView(FormView):
    success_url = reverse_lazy('core:index')
    form_class = LoginForm
    template_name = 'accounts/login.html'

    @method_decorator(sensitive_post_parameters('password'))
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        request.session.set_test_cookie()
        logout(request)

        return super(LoginView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        login(self.request, form.get_user())

        if self.request.session.test_cookie_worked():
            self.request.session.delete_test_cookie()

        return super(LoginView, self).form_valid(form)

guiadomilico/apps/accounts/views/views.py
from django.contrib.auth import login, logout
from django.core.validators import validate_email

from django.utils.decorators import method_decorator
from django.urls import reverse_lazy

from django.views.decorators.csrf import csrf_protect
from django.views.decorators.cache import never_cache
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import FormView

from django.shortcuts import render

from guiadomilico.apps.accounts.models.base import Usuario
from guiadomilico.apps.accounts.forms.base import LoginForm

# Create your views here.

class LoginView(FormView):
	success_url = reverse_lazy('core:index')
	form_class = LoginForm
	template_name = 'accounts/login.html'

	@method_decorator(sensitive_post_parameters('password'))
	@method_decorator(csrf_protect)
	@method_decorator(never_cache)
	def dispatch(self, request, *args, **kwargs):
		request.session.set_test_cookie()
		logout(request)

		return super(LoginView, self).dispatch(request, *args, **kwargs)

	def form_valid(self, form):
		login(self.request, form.get_user())

		if self.request.session.test_cookie_worked():
			self.request.session.delete_test_cookie()

		return super(LoginView, self).form_valid(form)

guiadomilico/apps/blog/views/base.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from guiadomilico.apps.blog.forms import PostForm
from guiadomilico.apps.blog.models import Post


def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'blog/post_list.html', {'posts': posts})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})

def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blog:detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'dashboard/post_edit.html', {'form': form})


def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blog:detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'dashboard/post_edit.html', {'form': form})

guiadomilico/apps/core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


# Create your views here.

class ShopView(TemplateView):
    template_name = "core/shop.html"

    ## FALTA IMPLEMENTAR ##

class IndexView(TemplateView):
    template_name = "core/index.html"

    ## FALTA IMPLEMENTAR ##

class SucessView(TemplateView):
    template_name = "accounts/active_sucess.html"

    ## FALTA IMPLEMENTAR ##

guiadomilico/apps/dashboard/views/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.utils import timezone
from guiadomilico.apps.blog.models import Post


class DashboardView(TemplateView):
    template_name = "dashboard/index.html"


def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'dashboard/post_list.html', {'posts': posts})

guiadomilico/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->
	<title>{%block title%} - Guia do Milico{%endblock%}</title>

{% block head %}
	{% include 'core/head.html' %}
{% endblock %}

<body>
	<!--[if lt IE 9]>
		<div class="bg-danger text-center">Você está usando um navegador <strong>desatualizado</strong>. Por favor <a href="http://browsehappy.com/" class="color-main">atualize seu navegador</a> para melhorar sua experiência.</div>
	<![endif]-->

	<div class="preloader">
		<div class="preloader_image"></div>
	</div>


	{% include 'core/modals.html' %}


	<!--noindex--><svg style="display:none" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
		<defs>


			<symbol id="icon-1" viewBox="0 0 226 32">
				<title>1</title>
				<path d="M18.942 13.058c-0.244-0.244-0.64-0.244-0.884 0l-2.683 2.683-0.808-0.808c-0.244-0.244-0.64-0.244-0.884 0s-0.244 0.64 0 0.884l1.25 1.25c0.122 0.122 0.282 0.183 0.442 0.183s0.32-0.061 0.442-0.183l3.125-3.125c0.244-0.244 0.244-0.64 0-0.884z"></path>
			</symbol>


			<symbol id="icon-2" viewBox="0 0 248 32">
				<title>2</title>
				<path d="M18.942 13.058c-0.244-0.244-0.64-0.244-0.884 0l-2.683 2.683-0.808-0.808c-0.244-0.244-0.64-0.244-0.884 0s-0.244 0.64 0 0.884l1.25 1.25c0.122 0.122 0.282 0.183 0.442 0.183s0.32-0.061 0.442-0.183l3.125-3.125c0.244-0.244 0.244-0.64 0-0.884z"></path>
			</symbol>

			<symbol id="icon-aim" viewBox="0 0 32 32">
				<title>aim</title>
				<path d="M29.776 13.776h-1.393c-0.265-6.424-5.442-11.601-11.866-11.866v-1.393c0-0.286-0.232-0.517-0.517-0.517s-0.517 0.232-0.517 0.517v1.393c-6.424 0.265-11.601 5.442-11.866 11.866h-1.393c-0.286 0-0.517 0.232-0.517 0.517s0.232 0.517 0.517 0.517h1.393c0.265 6.424 5.442 11.601 11.866 11.866v4.806c0 0.286 0.232 0.517 0.517 0.517s0.517-0.232 0.517-0.517v-4.806c6.424-0.265 11.601-5.442 11.866-11.866h1.393c0.286 0 0.517-0.232 0.517-0.517s-0.232-0.517-0.517-0.517zM15.483 25.641c-5.853-0.264-10.567-4.977-10.831-10.831h4.53c0.252 3.359 2.942 6.049 6.301 6.301v4.53zM15.483 20.072c-2.788-0.247-5.014-2.474-5.262-5.262h2.979c0.213 1.156 1.126 2.070 2.283 2.283v2.979zM15.483 16.031c-0.585-0.174-1.046-0.636-1.221-1.221h1.221v1.221zM14.262 13.776c0.174-0.585 0.636-1.046 1.221-1.221v1.221h-1.221zM13.2 13.776h-2.979c0.248-2.788 2.474-5.014 5.262-5.262v2.979h0c-1.156 0.213-2.069 1.126-2.283 2.283zM15.483 7.475c-3.359 0.252-6.049 2.942-6.301 6.301h-4.53c0.264-5.853 4.977-10.567 10.831-10.831v4.53zM16.517 8.514c2.788 0.248 5.014 2.474 5.262 5.262l-2.979 0c-0.213-1.156-1.126-2.070-2.283-2.283v-2.979zM16.517 12.555c0.585 0.174 1.046 0.636 1.221 1.221h-1.221v-1.221zM16.517 14.81h1.221c-0.174 0.585-0.636 1.046-1.221 1.221v-1.221zM18.8 14.81h2.979c-0.247 2.788-2.474 5.014-5.262 5.262v-2.979h-0c1.156-0.213 2.070-1.126 2.283-2.283zM16.517 25.641v-4.53c3.359-0.252 6.049-2.942 6.301-6.301h4.53c-0.264 5.853-4.977 10.567-10.831 10.831zM22.818 13.776c-0.252-3.359-2.942-6.049-6.301-6.301v-4.53c5.853 0.264 10.567 4.977 10.831 10.831h-4.53z"></path>
			</symbol>
		</defs>
	</svg>


{% block menu %}
	{% include 'menu/init.html' %}
{% endblock %}

{% block content %} {% endblock %}

{% include 'core/foo.html' %}

{% include 'core/scripts.html' %}


</body>

</html>

guiadomilico/templates/core/modals.html
{% load static %}

	<!-- MODAL PESQUISA -->
	<div class="modal" tabindex="-1" role="dialog" aria-labelledby="search_modal" id="search_modal">
		<button type="button" class="close" data-dismiss="modal" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
		<div class="widget widget_search">
			<form method="post" class="searchform search-form" action="" >
				{% csrf_token %}
				<div class="form-group">
					<input type="text" value="" name="search" class="form-control" placeholder="Encontrar no site..." id="modal-search-input">
				</div>
				<button type="submit" class="btn">Pesquisar</button>
			</form>
		</div>
	</div>



<!-- MODAL CADASTRAR -->
	<div class="modal" tabindex="-1" role="dialog" aria-labelledby="search_modal" id="sign_up_modal">
		<div class="container">
			<div class="row c-gutter-0 align-items-center">
				<div class="ls col-12 col-sm-6">
					<form class="contact-form sign-in c-mb-10 c-gutter-10" method="post" action="" >
						{% csrf_token %}
						<div class="row">
							<div class="col-sm-12">
								<h4><span class="color-main">Cadastro</span> / Login</h4>
								<div class="divider-sm-0 divider-md-30"></div>
								<div class="form-group has-placeholder">
									<label for="signupname">Nome Completo <span class="required">*</span></label>
									<input type="text" aria-required="true" size="30" value="" name="name" id="signupname" class="form-control" placeholder="Nome Completo">
								</div>
								<div class="form-group has-placeholder">
									<label for="signuppassword">Senha<span class="required">*</span></label>
									<input type="password" aria-required="true" size="30" value="" name="password" id="signuppassword" class="form-control" placeholder="Senha">
								</div>
								<div class="form-group has-placeholder">
									<label for="signupemail">E-mail<span class="required">*</span></label>
									<input type="email" aria-required="true" size="30" value="" name="email" id="signupemail" class="form-control" placeholder="E-mail">
								</div>
								<div>
									<input type="checkbox" class="checkbox" id="signupcheckbox" />
									<label for="signupcheckbox">Eu concordo com todo o texto do contrato</label>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-sm-12">
								<div class="form-group">
									<button type="submit" id="contact_signupform_submit" name="contact_submit" class="btn btn-outline-darkgrey">Enviar</button>
								</div>
							</div>
							<a class="phone_modal_button sign_up_modal close-modal" data-dismiss="modal" aria-label="Close" href="#sign_in_modal"><span aria-hidden="true">Eu já sou membro</span></a>
						</div>
					</form>
				</div>
				<div class="col-12 col-sm-6 d-none d-sm-block">
					<img src="{% static 'images/sing-in-modal.jpg' %}" alt="">
				</div>
			</div>
		</div>
	</div>




<!-- MODAL LOGIN -->
	<div class="modal" tabindex="-1" role="dialog" aria-labelledby="search_modal" id="sign_in_modal">
		<div class="container">
			<div class="row c-gutter-0 align-items-center">
				<div class="ls col-12 col-sm-6">
					<form class="contact-form  c-mb-10 c-gutter-10" method="post" action="{% url 'accounts:login' %}"  >
						{% csrf_token %}
						<div class="row">
							<div class="col-sm-12">
								<h4><span class="color-main">Entrar</span> / Login</h4>
								<div class="divider-sm-0 divider-md-30"></div>
								<div class="form-group ">
									<label for="username">E-mail ou usuário <span class="required">*</span></label>
									<input type="text" aria-required="true" size="30" value="" name="username" id="username" class="form-control" >
								</div>
								<div class="form-group has-placeholder">
									<label for="password">Senha<span class="required">*</span></label>
									<input type="password" aria-required="true" size="30" value="" name="password" id="password" class="form-control">
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-sm-12">
								<div class="form-group">
									<button type="submit" id="contact_signinform_submit" name="contact_submit" class="button">Entrar</button>
								</div>

															</div>


							<a class="sign_up_modal close-modal s-py-5" data-dismiss="modal" aria-label="Close" href="#sign_up_modal"><span aria-hidden="true">Esqueceu sua senha?</span></a>
							<br />

						</div>

							<a class=" link_cadastro" href="{% url 'accounts:cadastroUsuario'%} "><span aria-hidden="true">Quero me Cadastrar</span> </a>

					</form>

				</div>
				<div class="col-12 col-sm-6 d-none d-sm-block">
					<img src="{% static 'images/sing-in-modal.jpg' %}" alt="">
				</div>
			</div>
		</div>
	</div>




	<!-- Unyson messages modal -->
	<div class="modal fade" tabindex="-1" role="dialog" id="">
		<div class="fw-messages-wrap ls p-normal">
			<!-- Uncomment this UL with LI to show messages in modal popup to your user: -->
			<!--
		<ul class="list-unstyled">
			<li>Message To User</li>
		</ul>
		-->

		</div>
	</div><!-- eof .modal -->


<!-- Modal -->
<div class="modal fade" id="avatar_modal" tabindex="-1" role="dialog" aria-labelledby="avatar_modal" aria-hidden="true">
<div class="modal-dialog " role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Selecione o seu avatar</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
		 <!--
		  <a class="nav-avatar" href=""><img src="" width="90" /></a>
		   -->
      </div>

    </div>
  </div>
</div>