guiadomilico/apps/accounts/urls.py
from django.conf.urls import url
from django.urls import path

from guiadomilico.apps.accounts.views import login, cadastro

app_name = 'accounts'

urlpatterns = [
    url(r'login/$', login.LoginView.as_view(), name='login'),
    url(r'logout/$', login.LoginView.as_view(), name='logout'),
    path('cadastro/', cadastro.CadastroWizard.as_view(), name='cadastroUsuario'),
    path('my-account/<int:pk>', cadastro.CadastroUpdateView.as_view(), name='my-account'),
    path('confirm/<str:uidb64>/<str:token>', cadastro.ativarCadastro, name='cadastroAtivar'),
    path('cadastro/ativar-conta', cadastro.EmailActiveView.as_view(), name='ativar-conta'),
    path('cadastro/reenviar-email', cadastro.accounts_inactive, name='cadastroReenvioEmail'),
    path('cadastro/ativado', cadastro.ativadoSucesso, name='ativado'),
    url('ajax/is_exists_register_ajax/', cadastro.is_exists_register_ajax, name='is_exists_register_ajax'),
    url('ajax/verifica_cep/', cadastro.consultar_cep, name='verifica_cep'),

]

guiadomilico/apps/base/urls.py
from django.conf.urls import url
from . import views


app_name = 'base'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^loja-virtual/$', views.ShopView.as_view(), name='loja-virtual'),

]

guiadomilico/apps/blog/urls.py
from django.conf.urls import url
from .views import base

app_name = 'blog'
urlpatterns = [
    url(r'^$', base.post_list, name='list'),
    url(r'^post/(?P<pk>[0-9]+)/$', base.post_detail, name='detail'),
    url(r'^post/new/$', base.post_new, name='post_new'),
    url(r'^post/(?P<pk>[0-9]+)/edit/$', base.post_edit, name='post_edit'),
]

guiadomilico/urls.py
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url('admin/', admin.site.urls),
    #URL do app BASE:
    url(r'^', include('guiadomilico.apps.core.urls')),
    url(r'^accounts/', include('guiadomilico.apps.accounts.urls')),
    url(r'^dashboard/', include('guiadomilico.apps.dashboard.urls')),
    url(r'^blog/' , include('guiadomilico.apps.blog.urls')),
]

guiadomilico/apps/dashboard/models/models.py
from django.db import models

# Create your models here.

guiadomilico/apps/blog/forms/base.py
from django import forms

from guiadomilico.apps.blog.models import Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'text']

        labels = {
            'title':'Titulo da postagem',
            'text': 'Digite o conteúdo'
        }

        widgets = {
            'text': forms.Textarea(attrs={'hidden': 'hidden', '':'text'}),
        }

guiadomilico/apps/accounts/views/cadastro.py
from django.contrib.auth import logout, login

from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage, send_mail
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.urls import reverse_lazy, reverse
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views.generic import FormView, TemplateView
from guiadomilico.apps.accounts.forms import EnderecoFormSet, TelefoneFormSet
from guiadomilico.apps.accounts.token import account_activation_token
from guiadomilico.apps.accounts.forms.cadastro import CadastroUserForm, CadastroUpdateForm
from guiadomilico.apps.accounts.models.base import Usuario, Endereco
from formtools.wizard.views import SessionWizardView
from  django.views.generic.edit import UpdateView
from  django.views.generic.list import ListView

import pycep_correios as pycep

from ..models import *

def send_mail(request, usuario):
    current_site = get_current_site(request)
    mail_subject = "[Guia do Milico] Ativação de usuário necessária"
    message = render_to_string('accounts/email_ativacao.html', {
        'usuario': usuario,
        'dominio': current_site.domain,
        'uid': urlsafe_base64_encode(force_bytes(usuario.pk)),
        'token': account_activation_token.make_token(usuario),
    })
    to_email = usuario.email

    email = EmailMessage(
        mail_subject,
        message,
        to=[to_email]
    )

    email.send()


## VIEW EM DESENVOLVIMENTO ##
class CadastroUpdateView(UpdateView):
    template_name = 'accounts/my_account.html'
    model = Usuario
    form_class = CadastroUpdateForm
    context_object_name = "usuario"

    def get_success_url(self):
        id = self.kwargs.get(self.pk_url_kwarg)
        return reverse_lazy('accounts:my-account', kwargs={'pk': id })

    def get_context_data(self, **kwargs):
        id = self.kwargs.get(self.pk_url_kwarg)
        kwargs['usuario'] = Usuario.objects.filter(id=id).first()
        kwargs['usuario_form'] = CadastroUpdateForm(self.request.POST or None, instance=kwargs['usuario'])
        kwargs['endereco'] = list(Endereco.objects.filter(usuario_end__pk=self.kwargs['pk']).values())
        kwargs['TIPO_ENDERECO'] = TIPO_ENDERECO
        return super().get_context_data(**kwargs)



class CadastroListView(ListView):
    template_name = 'accounts/my_account.html'
    model = Usuario
    form_class = CadastroUserForm
    context_object_name = "usuario"


class EnderecoListView(ListView):
    template_name = 'accounts/my_account.html'
    model = Usuario
    form_class = CadastroUserForm
    context_object_name = "usuario"

class CadastroWizard(SessionWizardView):
    template_name = 'accounts/cadastro_usuario.html'

    FORMS = [("usuario", CadastroUserForm),
             ("endereco", EnderecoFormSet),
             ("telefone", TelefoneFormSet)
             ]

    form_list = FORMS


    def done(self, form_list, form_dict, **kwargs):

        template_name = 'accounts/email_notification.html'
        context = {}
        form_data = [form.cleaned_data for form in form_list]
        usuario = CadastroUserForm(form_data[0])
        user = usuario.save(commit=False)
        usuario.is_trusty = False
        instance = usuario.save()

        if 'endereco' in form_dict:
            formset = form_dict['endereco']
            if formset.is_valid():
                formset.instance = instance
                instance_endereco = formset.save()
                usuario.endereco_padrao = instance_endereco


        if 'telefone' in form_dict:
            formset = form_dict['telefone']
            if formset.is_valid():
                formset.instance = instance
                instance_telefone = formset.save()
                usuario.telefone_padrao = instance_telefone

        usuario.save()
        send_mail(self.request, user)

        # Context para avisar ao usuário que o cadastro foi efetuado com sucesso.
        # self.extra_context['form'] = self.get_form_instance(0)

        context['nomeCompleto'] = instance.get_full_name()
        context["emailEnvio"] = instance.email
        context["sucessoCadastro"] = "Um email foi enviado para {} com um link de ativação.".format(instance.email)

        return render(self.request, template_name, context )


'''
class CadastroUserView(FormView):
    form_class = CadastroUserForm
    template_name = 'accounts/cadastro_usuario.html'
    
    extra_context = {}
    endereco = EnderecoFormSet(prefix='endereco')
    telefone = TelefoneFormSet(prefix='telefone')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context["endereco"] = EnderecoFormSet(self.request.POST)
            context["telefone"] = TelefoneFormSet(self.request.POST)

        else:
            context["endereco"] = EnderecoFormSet()
            context["telefone"] = TelefoneFormSet()

        return context

    def get(self, request, *args, **kwargs):

        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        endereco = EnderecoFormSet()
        telefone = TelefoneFormSet()

        return self.render_to_response(
            self.get_context_data(form=form,
                                  endereco=endereco,
                                  telefone=telefone
                                  )
        )

    def post(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        endereco = EnderecoFormSet(self.request.POST)
        telefone = TelefoneFormSet(self.request.POST)

        if form.is_valid() and endereco.is_valid():
            return self.form_valid(form, endereco, telefone)
        else:
            return self.form_invalid(form, endereco, telefone)

    def form_valid(self, form, endereco, telefone):
        usuario = form.save(commit=False)
        usuario.is_trusty = False
        self.object = form.save()
        endereco.instance = self.object
        endereco.save()
        telefone.instance = self.object
        telefone.save()
        send_mail(self.request, usuario)

        # Context para avisar ao usuário que o cadastro foi efetuado com sucesso.
        self.extra_context['form'] = self.form_class

        self.extra_context['nomeCompleto'] = "{} {}".format(usuario.nome, usuario.sobrenome)
        self.request.session["emailEnvio"] = usuario.email
        self.request.session["sucessoCadastro"] = "Um email foi enviado para {} com um link de ativação.".format(
            usuario.email)

        return super(CadastroUserView, self).form_valid(form)

    def form_invalid(self, form, endereco, telefone):

        return self.render_to_response(
            self.get_context_data(form=form,
                                  endereco=endereco,
                                  telefone=telefone
                                  )
        )

'''


def ativadoSucesso(request):
    template_name = 'accounts/active_sucess.html'
    return render(request, template_name)


def ativa(uidb64, token):
    _return = {}
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = Usuario.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, Usuario.DoesNotExist):
        user = None

    if user is not None:
        if account_activation_token.check_token(user, token):
            user.is_trusty = True
            user.save()
        else:
            user = None
            _return['erro'] = 'Token inválido ou já utilizado!'
    else:
        _return['erro'] = 'Usuário inválido!'
    _return['usuario'] = user
    return _return


def ativarCadastro(request, uidb64, token):
    logout(request)

    _return = ativa(uidb64, token)
    if _return['usuario']:
        login(request, _return['usuario'])
        return redirect('accounts:ativado')
    else:
        context = {}
        context['erro'] = _return['erro']
        template_name = 'accounts/login.html'
        return render(request, template_name, context)


class EmailActiveView(TemplateView):
    template_name = 'accounts/email_notification.html'

    def get_context_data(self, **kwargs):
        context = super(EmailActiveView, self).get_context_data(**kwargs)
        context['sucessoCadastro'] = self.request.session["sucessoCadastro"]
        context['emailEnvio'] = self.request.session["emailEnvio"]
        del self.request.session["sucessoCadastro"]
        del self.request.session["emailEnvio"]

        return context


def accounts_inactive(request):
    logout(request)
    template_name = 'accounts/cadastro_inativo.html'
    context = {}

    if request.method == 'POST':
        username = request.POST['username']

        if Usuario.objects.filter(email=username).count() == 1:
            usuario = Usuario.objects.get(email=username)
        elif Usuario.objects.filter(username=username).count() == 1:
            usuario = Usuario.objects.get(username=username)
        else:
            usuario = None

        if usuario is not None:
            send_mail(request, usuario)

            request.session['sucessoCadastro'] = "Um email foi enviado para {} com um link de ativação.".format(
                usuario.email)
            request.session['emailEnvio'] = usuario.email

            return redirect(reverse('accounts:ativar-conta'))

        else:
            context['erro'] = "Nome de usuário/Email não encontrado!"

        return render(request, template_name, context)

    return render(request, template_name, context)


def is_exists_register_ajax(request):
    field = request.GET.get('field', None)
    validate = request.GET.get('validate', None)

    if validate is not None:
        if validate == 'username':

guiadomilico/apps/accounts/views/login.py
from django.contrib.auth import login, logout
from django.core.validators import validate_email

from django.utils.decorators import method_decorator
from django.urls import reverse_lazy

from django.views.decorators.csrf import csrf_protect
from django.views.decorators.cache import never_cache
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import FormView, RedirectView

from django.shortcuts import render

from guiadomilico.apps.accounts.models.base import Usuario
from guiadomilico.apps.accounts.forms.login import LoginForm


# Create your views here.

class LoginView(FormView):
    success_url = reverse_lazy('core:index')
    form_class = LoginForm
    template_name = 'accounts/login.html'

    @method_decorator(sensitive_post_parameters('password'))
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        request.session.set_test_cookie()
        logout(request)

        return super(LoginView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        login(self.request, form.get_user())

        if self.request.session.test_cookie_worked():
            self.request.session.delete_test_cookie()

        return super(LoginView, self).form_valid(form)

guiadomilico/apps/accounts/views/views.py
from django.contrib.auth import login, logout
from django.core.validators import validate_email

from django.utils.decorators import method_decorator
from django.urls import reverse_lazy

from django.views.decorators.csrf import csrf_protect
from django.views.decorators.cache import never_cache
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import FormView

from django.shortcuts import render

from guiadomilico.apps.accounts.models.base import Usuario
from guiadomilico.apps.accounts.forms.base import LoginForm

# Create your views here.

class LoginView(FormView):
	success_url = reverse_lazy('core:index')
	form_class = LoginForm
	template_name = 'accounts/login.html'

	@method_decorator(sensitive_post_parameters('password'))
	@method_decorator(csrf_protect)
	@method_decorator(never_cache)
	def dispatch(self, request, *args, **kwargs):
		request.session.set_test_cookie()
		logout(request)

		return super(LoginView, self).dispatch(request, *args, **kwargs)

	def form_valid(self, form):
		login(self.request, form.get_user())

		if self.request.session.test_cookie_worked():
			self.request.session.delete_test_cookie()

		return super(LoginView, self).form_valid(form)

guiadomilico/apps/blog/views/base.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from guiadomilico.apps.blog.forms import PostForm
from guiadomilico.apps.blog.models import Post


def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'blog/post_list.html', {'posts': posts})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})

def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blog:detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'dashboard/post_edit.html', {'form': form})


def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blog:detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'dashboard/post_edit.html', {'form': form})

guiadomilico/apps/core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


# Create your views here.

class ShopView(TemplateView):
    template_name = "core/shop.html"

    ## FALTA IMPLEMENTAR ##

class IndexView(TemplateView):
    template_name = "core/index.html"

    ## FALTA IMPLEMENTAR ##

class SucessView(TemplateView):
    template_name = "accounts/active_sucess.html"

    ## FALTA IMPLEMENTAR ##

guiadomilico/apps/dashboard/views/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.utils import timezone
from guiadomilico.apps.blog.models import Post


class DashboardView(TemplateView):
    template_name = "dashboard/index.html"


def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'dashboard/post_list.html', {'posts': posts})

guiadomilico/templates/accounts/active_sucess.html
{% extends 'core/base.html' %}
{% block title %}Ativado com sucesso | {{ block.super }}{% endblock %}
{% block menu %}
{% include 'menu/fix.html' %}
{% endblock %}

{%block content %}
<section class="page_title padding-mobile cs s-py-60 s-py-md-80 s-py-xl-50 cover-background">
					<div class="container">
						<div class="row">


							<div class="col-md-12">
								<h1 class="bold">SEJA BEM VINDO</h1>
								<ul class="breadcrumb">
									<li class="breadcrumb-item">
											Conheça mais os <a href="{% url 'accounts:cadastroUsuario'%} " > Nossos Serviços </a>
									</li>
								</ul>
							</div>

						</div>
					</div>
				</section>

         <section class="ls s-py-25">
				<div class="container">
					<div class="row">

						<div class="d-none d-lg-block divider-70"></div>

						<main class="col-lg-12">
							<article>
								<!-- .entry-header -->
								<div class="entry-content">
									<div class="woocommerce">

<div class="icon-box text-center hero-bg rounded box-shadow animate" data-animation="slideUp" data-delay="150" >
										<div class="icon-styled bg-maincolor3 rounded fs-24">
											<i class="fa fa-check"></i>
										</div>
										<h6 class="fw-300">Ativada com sucesso.</h6>
										<p>Parabéns {{ user.get_full_name|title  }}, sua conta foi ativada com sucesso! Agora você pode utilizar todos os nossos serviços.</p>

</div>







                                        			</div>
								</div>
								<!-- .entry-content -->
							</article>


						</main>

						<div class="d-none d-lg-block divider-70"></div>
					</div>

				</div>
			</section>

{% endblock %}

guiadomilico/templates/accounts/cadastro_inativo.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Ativar conta | {{ block.super }}{% endblock %}
{% block menu %}
{% include 'menu/fix.html' %}
{% endblock %}

{% block content %}
<section class="page_title padding-mobile cs s-py-60 s-py-md-80 s-py-xl-50 cover-background">
					<div class="container">
						<div class="row">


							<div class="col-md-12">
								<h1 class="bold">ATIVAR CONTA</h1>
								<ul class="breadcrumb">
									<li class="breadcrumb-item">
											Ainda não possui cadastro? <a href="{% url 'accounts:cadastroUsuario'%} " > Cadastrar-se </a>
									</li>
								</ul>
							</div>

						</div>
					</div>
				</section>
         <section class="ls s-py-25">
				<div class="container">
					<div class="row">

						<div class="d-none d-lg-block divider-70"></div>

						<main class="col-lg-12">
							<article>
								<!-- .entry-header -->
								<div class="entry-content">
									<div class="woocommerce">

										<!--
			<div class="woocommerce-message">Are you sure you want to log out? <a
				href="shop-account-login.html">Confirm and log out</a>
			</div>
			-->

										<form class="woocomerce-form woocommerce-form-login login" method="post" novalidate>
										{% csrf_token %}

											<p class="woocommerce-form-row woocommerce-form-row--wide form-row form-row-wide">
												<label for="username">Usuário / E-mail <span class="required">*</span></label>
												<input type="text" class="woocommerce-Input woocommerce-Input--text input-text" name="username" placeholder="Digite o e-mail que cadastrou e pressione [ Enter ]" id="username" value="">
											</p>



										</form>



									</div>
								</div>
								<!-- .entry-content -->
							</article>


						</main>

						<div class="d-none d-lg-block divider-70"></div>
					</div>

				</div>
			</section>

{% endblock %}

guiadomilico/templates/accounts/email_ativacao.html
{% autoescape off %}
Ola {{ usuario.username }},

O Guia do Milico tem a satisfação em receber sua solicitação de cadastro em nosso site.
Como uma forma de manter nossos usuários seguros, solicitamos que você clique no link abaixo para confirmar seu registro:

https://{{ dominio }}{% url 'accounts:cadastroAtivar' uidb64=uid token=token %}

Caso você não se sinta seguro em utilizar o link acima, você pode confirmar seu registro digitando o seguinte endereço em seu navegador e digitar o código de ativação:

https://{{ dominio }}/accounts/ativar

User id: {{ uid }}
Código de ativação: {{ token }}

Respeitosamente,

Equipe Guia do Milico
{% endautoescape %}

guiadomilico/templates/accounts/email_notification.html
{% extends 'core/base.html' %}
{% block title %}Ative sua conta | {{ block.super }}{% endblock %}
{% block menu %}
{% include 'menu/fix.html' %}
{% endblock %}

{%block content %}

         <section class="ls s-py-25">
				<div class="container">
					<div class="row">

						<div class="d-none d-lg-block divider-70"></div>

						<main class="col-lg-12">
							<article>
								<!-- .entry-header -->
								<div class="entry-content">
									<div class="woocommerce">

										<div class="icon-box text-center hero-bg rounded box-shadow animate" data-animation="slideUp" data-delay="150" >
											{% if sucessoCadastro %}
												<div class="icon-styled bg-maincolor rounded fs-24">
													<i class="fa fa-envelope"></i>
												</div>
												<h6 class="fw-300">Email de ativação.</h6>
												<p>

														{{ sucessoCadastro }}


												</p>
												<p>
													<a href="{% url 'accounts:cadastroReenvioEmail' %}">Reenviar email</a>
												</p>
											{% endif %}
										</div>

                  </div>
								</div>
								<!-- .entry-content -->
							</article>


						</main>

						<div class="d-none d-lg-block divider-70"></div>
					</div>

				</div>
			</section>

{% endblock %}

guiadomilico/templates/accounts/login.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Acessar sua conta{{ block.super }}{% endblock %}
{% block menu %}
{% include 'menu/fix.html' %}
{% endblock %}

{% block content %}




<div class="d-none d-lg-block divider-30 "></div>
				<div class="container">
					<h5>Identificação</h5>
					<div class="row">


	<div class="col-lg-6">
							<div class="card shadow-sm">
								<!-- .entry-header -->
							<div class="card-header">
											<h3 class="special-heading text-center"> Quero criar uma conta</h3>
											
										</div>

								<div class="entry-content card-body">
									<div class="woocommerce">

										<!--
			<div class="woocommerce-message">Are you sure you want to log out? <a
				href="shop-account-login.html">Confirm and log out</a>
			</div>
			-->

										<form class="woocomerce-form " method="post" 	>
										{% csrf_token %}

											<p class="woocommerce-form-row woocommerce-form-row--wide form-row form-row-wide">
												<label for="username">E-mail <span class="required">*</span>
												</label>
												<input type="text" required class=" form-control woocommerce-Input woocommerce-Input--text input-text" name="username" id="username" value="">
											</p>
											
											<p class="form-row">
												<input type="submit" class="button" name="login" value="Continuar">

						
											</p>
											<p class="woocommerce-LostPassword lost_password">
												Dúvidas? <a href="shop-account-password-reset.html">fale conosco</a>
											</p>


										</form>



									</div>
								</div>
								<!-- .entry-content -->
							</div>


						</div>

						<div class="col-lg-6">
							<div class="card shadow-sm">
								<!-- .entry-header -->
								<div class="card-header">
									<h1 class="special-heading text-center"> Já sou cadastrado</h1>
								</div>
								<div class="card-body">
									<div class="woocommerce">

										<!--
			<div class="woocommerce-message">Are you sure you want to log out? <a
				href="shop-account-login.html">Confirm and log out</a>
			</div>
			-->

										<form class="woocomerce-form " method="post" 	>
										{% csrf_token %}

											<p class="woocommerce-form-row woocommerce-form-row--wide form-row form-row-wide">
												<label for="username">Usuário ou E-mail <span class="required">*</span>
												</label>
												<input type="text" required class=" form-control  woocommerce-Input woocommerce-Input--text input-text" name="username" id="username" value="">
											</p>
											<p class="woocommerce-form-row woocommerce-form-row--wide form-row form-row-wide">
												<label for="woo-password">Senha <span class="required">*</span>
												</label>
												<input required class=" form-control  woocommerce-Input woocommerce-Input--text input-text" type="password" name="password" id="woo-password">
											</p>
		<p class="woocommerce-LostPassword lost_password">

											</p>
											<p class="form-row">
												<input type="submit" class=" button" name="login" value="Continuar">

												<label class="woocommerce-form__label woocommerce-form__label-for-checkbox mt-3">
													<input class="woocommerce-form__input woocommerce-form__input-checkbox" name="rememberme" type="checkbox" id="rememberme" value="forever">
													<span>Mantenha-me conectado</span>
												</label>
											</p>
											<p class="woocommerce-LostPassword lost_password">
												Esqueci meu <a href="shop-account-password-reset.html">e-mail</a> ou a <a href="shop-account-password-reset.html">senha</a>
											</p>


										</form>



									</div>
								</div>
								<!-- .entry-content -->
							</div>


						</div>

						<div class="d-none d-lg-block divider-70"></div>
					</div>

				</div>
			</section>

{% endblock %}