guiadomilico/apps/accounts/urls.py
from django.conf.urls import url
from django.urls import path

from guiadomilico.apps.accounts.views import login, cadastro

app_name = 'accounts'

urlpatterns = [
    url(r'login/$', login.LoginView.as_view(), name='login'),
    url(r'logout/$', login.LoginView.as_view(), name='logout'),
    path('cadastro/', cadastro.CadastroWizard.as_view(), name='cadastroUsuario'),
    path('my-account/<int:pk>', cadastro.CadastroUpdateView.as_view(), name='my-account'),
    path('confirm/<str:uidb64>/<str:token>', cadastro.ativarCadastro, name='cadastroAtivar'),
    path('cadastro/ativar-conta', cadastro.EmailActiveView.as_view(), name='ativar-conta'),
    path('cadastro/reenviar-email', cadastro.accounts_inactive, name='cadastroReenvioEmail'),
    path('cadastro/ativado', cadastro.ativadoSucesso, name='ativado'),
    url('ajax/is_exists_register_ajax/', cadastro.is_exists_register_ajax, name='is_exists_register_ajax'),
    url('ajax/verifica_cep/', cadastro.consultar_cep, name='verifica_cep'),

]

guiadomilico/apps/base/urls.py
from django.conf.urls import url
from . import views


app_name = 'base'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^loja-virtual/$', views.ShopView.as_view(), name='loja-virtual'),

]

guiadomilico/apps/blog/urls.py
from django.conf.urls import url
from .views import base

app_name = 'blog'
urlpatterns = [
    url(r'^$', base.post_list, name='list'),
    url(r'^post/(?P<pk>[0-9]+)/$', base.post_detail, name='detail'),
    url(r'^post/new/$', base.post_new, name='post_new'),
    url(r'^post/(?P<pk>[0-9]+)/edit/$', base.post_edit, name='post_edit'),
]

guiadomilico/apps/dashboard/urls.py
from django.conf.urls import url
from . import views
from .views.views import DashboardView

app_name = 'dashboard'
urlpatterns = [
    url(r'^$', DashboardView.as_view(), name='index'),
    url(r'^posts$', views.views.post_list, name='posts'),
]

guiadomilico/urls.py
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url('admin/', admin.site.urls),
    #URL do app BASE:
    url(r'^', include('guiadomilico.apps.core.urls')),
    url(r'^accounts/', include('guiadomilico.apps.accounts.urls')),
    url(r'^dashboard/', include('guiadomilico.apps.dashboard.urls')),
    url(r'^blog/' , include('guiadomilico.apps.blog.urls')),
]

guiadomilico/apps/blog/forms/base.py
from django import forms

from guiadomilico.apps.blog.models import Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'text']

        labels = {
            'title':'Titulo da postagem',
            'text': 'Digite o conteúdo'
        }

        widgets = {
            'text': forms.Textarea(attrs={'hidden': 'hidden', '':'text'}),
        }

guiadomilico/apps/accounts/views/cadastro.py
from django.contrib.auth import logout, login

from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage, send_mail
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.urls import reverse_lazy, reverse
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views.generic import FormView, TemplateView
from guiadomilico.apps.accounts.forms import EnderecoFormSet, TelefoneFormSet
from guiadomilico.apps.accounts.token import account_activation_token
from guiadomilico.apps.accounts.forms.cadastro import CadastroUserForm, CadastroUpdateForm
from guiadomilico.apps.accounts.models.base import Usuario, Endereco
from formtools.wizard.views import SessionWizardView
from  django.views.generic.edit import UpdateView
from  django.views.generic.list import ListView

import pycep_correios as pycep

from ..models import *

def send_mail(request, usuario):
    current_site = get_current_site(request)
    mail_subject = "[Guia do Milico] Ativação de usuário necessária"
    message = render_to_string('accounts/email_ativacao.html', {
        'usuario': usuario,
        'dominio': current_site.domain,
        'uid': urlsafe_base64_encode(force_bytes(usuario.pk)),
        'token': account_activation_token.make_token(usuario),
    })
    to_email = usuario.email

    email = EmailMessage(
        mail_subject,
        message,
        to=[to_email]
    )

    email.send()


## VIEW EM DESENVOLVIMENTO ##
class CadastroUpdateView(UpdateView):
    template_name = 'accounts/my_account.html'
    model = Usuario
    form_class = CadastroUpdateForm
    context_object_name = "usuario"

    def get_success_url(self):
        id = self.kwargs.get(self.pk_url_kwarg)
        return reverse_lazy('accounts:my-account', kwargs={'pk': id })

    def get_context_data(self, **kwargs):
        id = self.kwargs.get(self.pk_url_kwarg)
        kwargs['usuario'] = Usuario.objects.filter(id=id).first()
        kwargs['usuario_form'] = CadastroUpdateForm(self.request.POST or None, instance=kwargs['usuario'])
        kwargs['endereco'] = list(Endereco.objects.filter(usuario_end__pk=self.kwargs['pk']).values())
        kwargs['TIPO_ENDERECO'] = TIPO_ENDERECO
        return super().get_context_data(**kwargs)



class CadastroListView(ListView):
    template_name = 'accounts/my_account.html'
    model = Usuario
    form_class = CadastroUserForm
    context_object_name = "usuario"


class EnderecoListView(ListView):
    template_name = 'accounts/my_account.html'
    model = Usuario
    form_class = CadastroUserForm
    context_object_name = "usuario"

class CadastroWizard(SessionWizardView):
    template_name = 'accounts/cadastro_usuario.html'

    FORMS = [("usuario", CadastroUserForm),
             ("endereco", EnderecoFormSet),
             ("telefone", TelefoneFormSet)
             ]

    form_list = FORMS


    def done(self, form_list, form_dict, **kwargs):

        template_name = 'accounts/email_notification.html'
        context = {}
        form_data = [form.cleaned_data for form in form_list]
        usuario = CadastroUserForm(form_data[0])
        user = usuario.save(commit=False)
        usuario.is_trusty = False
        instance = usuario.save()

        if 'endereco' in form_dict:
            formset = form_dict['endereco']
            if formset.is_valid():
                formset.instance = instance
                instance_endereco = formset.save()
                usuario.endereco_padrao = instance_endereco


        if 'telefone' in form_dict:
            formset = form_dict['telefone']
            if formset.is_valid():
                formset.instance = instance
                instance_telefone = formset.save()
                usuario.telefone_padrao = instance_telefone

        usuario.save()
        send_mail(self.request, user)

        # Context para avisar ao usuário que o cadastro foi efetuado com sucesso.
        # self.extra_context['form'] = self.get_form_instance(0)

        context['nomeCompleto'] = instance.get_full_name()
        context["emailEnvio"] = instance.email
        context["sucessoCadastro"] = "Um email foi enviado para {} com um link de ativação.".format(instance.email)

        return render(self.request, template_name, context )


'''
class CadastroUserView(FormView):
    form_class = CadastroUserForm
    template_name = 'accounts/cadastro_usuario.html'
    
    extra_context = {}
    endereco = EnderecoFormSet(prefix='endereco')
    telefone = TelefoneFormSet(prefix='telefone')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context["endereco"] = EnderecoFormSet(self.request.POST)
            context["telefone"] = TelefoneFormSet(self.request.POST)

        else:
            context["endereco"] = EnderecoFormSet()
            context["telefone"] = TelefoneFormSet()

        return context

    def get(self, request, *args, **kwargs):

        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        endereco = EnderecoFormSet()
        telefone = TelefoneFormSet()

        return self.render_to_response(
            self.get_context_data(form=form,
                                  endereco=endereco,
                                  telefone=telefone
                                  )
        )

    def post(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        endereco = EnderecoFormSet(self.request.POST)
        telefone = TelefoneFormSet(self.request.POST)

        if form.is_valid() and endereco.is_valid():
            return self.form_valid(form, endereco, telefone)
        else:
            return self.form_invalid(form, endereco, telefone)

    def form_valid(self, form, endereco, telefone):
        usuario = form.save(commit=False)
        usuario.is_trusty = False
        self.object = form.save()
        endereco.instance = self.object
        endereco.save()
        telefone.instance = self.object
        telefone.save()
        send_mail(self.request, usuario)

        # Context para avisar ao usuário que o cadastro foi efetuado com sucesso.
        self.extra_context['form'] = self.form_class

        self.extra_context['nomeCompleto'] = "{} {}".format(usuario.nome, usuario.sobrenome)
        self.request.session["emailEnvio"] = usuario.email
        self.request.session["sucessoCadastro"] = "Um email foi enviado para {} com um link de ativação.".format(
            usuario.email)

        return super(CadastroUserView, self).form_valid(form)

    def form_invalid(self, form, endereco, telefone):

        return self.render_to_response(
            self.get_context_data(form=form,
                                  endereco=endereco,
                                  telefone=telefone
                                  )
        )

'''


def ativadoSucesso(request):
    template_name = 'accounts/active_sucess.html'
    return render(request, template_name)


def ativa(uidb64, token):
    _return = {}
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = Usuario.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, Usuario.DoesNotExist):
        user = None

    if user is not None:
        if account_activation_token.check_token(user, token):
            user.is_trusty = True
            user.save()
        else:
            user = None
            _return['erro'] = 'Token inválido ou já utilizado!'
    else:
        _return['erro'] = 'Usuário inválido!'
    _return['usuario'] = user
    return _return


def ativarCadastro(request, uidb64, token):
    logout(request)

    _return = ativa(uidb64, token)
    if _return['usuario']:
        login(request, _return['usuario'])
        return redirect('accounts:ativado')
    else:
        context = {}
        context['erro'] = _return['erro']
        template_name = 'accounts/login.html'
        return render(request, template_name, context)


class EmailActiveView(TemplateView):
    template_name = 'accounts/email_notification.html'

    def get_context_data(self, **kwargs):
        context = super(EmailActiveView, self).get_context_data(**kwargs)
        context['sucessoCadastro'] = self.request.session["sucessoCadastro"]
        context['emailEnvio'] = self.request.session["emailEnvio"]
        del self.request.session["sucessoCadastro"]
        del self.request.session["emailEnvio"]

        return context


def accounts_inactive(request):
    logout(request)
    template_name = 'accounts/cadastro_inativo.html'
    context = {}

    if request.method == 'POST':
        username = request.POST['username']

        if Usuario.objects.filter(email=username).count() == 1:
            usuario = Usuario.objects.get(email=username)
        elif Usuario.objects.filter(username=username).count() == 1:
            usuario = Usuario.objects.get(username=username)
        else:
            usuario = None

        if usuario is not None:
            send_mail(request, usuario)

            request.session['sucessoCadastro'] = "Um email foi enviado para {} com um link de ativação.".format(
                usuario.email)
            request.session['emailEnvio'] = usuario.email

            return redirect(reverse('accounts:ativar-conta'))

        else:
            context['erro'] = "Nome de usuário/Email não encontrado!"

        return render(request, template_name, context)

    return render(request, template_name, context)


def is_exists_register_ajax(request):
    field = request.GET.get('field', None)
    validate = request.GET.get('validate', None)

    if validate is not None:
        if validate == 'username':

guiadomilico/apps/accounts/views/login.py
from django.contrib.auth import login, logout
from django.core.validators import validate_email

from django.utils.decorators import method_decorator
from django.urls import reverse_lazy

from django.views.decorators.csrf import csrf_protect
from django.views.decorators.cache import never_cache
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import FormView, RedirectView

from django.shortcuts import render

from guiadomilico.apps.accounts.models.base import Usuario
from guiadomilico.apps.accounts.forms.login import LoginForm


# Create your views here.

class LoginView(FormView):
    success_url = reverse_lazy('core:index')
    form_class = LoginForm
    template_name = 'accounts/login.html'

    @method_decorator(sensitive_post_parameters('password'))
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        request.session.set_test_cookie()
        logout(request)

        return super(LoginView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        login(self.request, form.get_user())

        if self.request.session.test_cookie_worked():
            self.request.session.delete_test_cookie()

        return super(LoginView, self).form_valid(form)

guiadomilico/apps/accounts/views/views.py
from django.contrib.auth import login, logout
from django.core.validators import validate_email

from django.utils.decorators import method_decorator
from django.urls import reverse_lazy

from django.views.decorators.csrf import csrf_protect
from django.views.decorators.cache import never_cache
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import FormView

from django.shortcuts import render

from guiadomilico.apps.accounts.models.base import Usuario
from guiadomilico.apps.accounts.forms.base import LoginForm

# Create your views here.

class LoginView(FormView):
	success_url = reverse_lazy('core:index')
	form_class = LoginForm
	template_name = 'accounts/login.html'

	@method_decorator(sensitive_post_parameters('password'))
	@method_decorator(csrf_protect)
	@method_decorator(never_cache)
	def dispatch(self, request, *args, **kwargs):
		request.session.set_test_cookie()
		logout(request)

		return super(LoginView, self).dispatch(request, *args, **kwargs)

	def form_valid(self, form):
		login(self.request, form.get_user())

		if self.request.session.test_cookie_worked():
			self.request.session.delete_test_cookie()

		return super(LoginView, self).form_valid(form)

guiadomilico/apps/blog/views/base.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from guiadomilico.apps.blog.forms import PostForm
from guiadomilico.apps.blog.models import Post


def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'blog/post_list.html', {'posts': posts})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})

def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blog:detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'dashboard/post_edit.html', {'form': form})


def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blog:detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'dashboard/post_edit.html', {'form': form})

guiadomilico/apps/core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


# Create your views here.

class ShopView(TemplateView):
    template_name = "core/shop.html"

    ## FALTA IMPLEMENTAR ##

class IndexView(TemplateView):
    template_name = "core/index.html"

    ## FALTA IMPLEMENTAR ##

class SucessView(TemplateView):
    template_name = "accounts/active_sucess.html"

    ## FALTA IMPLEMENTAR ##

guiadomilico/apps/dashboard/views/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.utils import timezone
from guiadomilico.apps.blog.models import Post


class DashboardView(TemplateView):
    template_name = "dashboard/index.html"


def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'dashboard/post_list.html', {'posts': posts})

guiadomilico/templates/menu/fix.html
{% load static %}

<header class="page_header s-overlay ds justify-nav-end">
					<div class="container">
						<div class="row align-items-center">
							<div class="col-xl-2 col-lg-3 col-md-4 col-11">
								<a href="{% url 'core:index' %}" class="logo">
									<img src="{% static 'images/logo.png' %}" alt="">
								</a>
							</div>
							<div class="col-xl-10 col-lg-9 col-md-8 col-1">
								<div class="nav-wrap">

									<!-- main nav start -->
									<nav class="top-nav">
										<ul class="nav sf-menu">

											<li>
												<a href="{% url 'core:index' %}">PRINCIPAL</a>

											</li>

											<li>
												<a href="about.html">O GUIA</a>
													<div class="mega-menu">
													<ul class="mega-menu-row">
														<li class="mega-menu-col">
															<a href="#">Headers</a>
															<ul>
																<li>
																	<a href="header1.html">Header Type 1</a>
																</li>
																<li>
																	<a href="header2.html">Header Type 2</a>
																</li>
																<li>
																	<a href="header3.html">Header Type 3</a>
																</li>
																<li>
																	<a href="header4.html">Header Type 4</a>
																</li>
																<li>
																	<a href="header5.html">Header Type 5</a>
																</li>
																<li>
																	<a href="header6.html">Header Type 6</a>
																</li>
															</ul>
														</li>
														<li class="mega-menu-col">
															<a href="#">Side Menus</a>
															<ul>
																<li>
																	<a href="header-side.html">Push Left</a>
																</li>
																<li>
																	<a href="header-side-right.html">Push Right</a>
																</li>
																<li>
																	<a href="header-side-slide.html">Slide Left</a>
																</li>
																<li>
																	<a href="header-side-slide-right.html">Slide Right</a>
																</li>
																<li>
																	<a href="header-side-sticked.html">Sticked Left</a>
																</li>
																<li>
																	<a href="header-side-sticked-right.html">Sticked Right</a>
																</li>
															</ul>
														</li>
														<li class="mega-menu-col">
															<a href="title1.html">Title Sections</a>
															<ul>
																<li>
																	<a href="title1.html">Title section 1</a>
																</li>
																<li>
																	<a href="title2.html">Title section 2</a>
																</li>
																<li>
																	<a href="title3.html">Title section 3</a>
																</li>
																<li>
																	<a href="title4.html">Title section 4</a>
																</li>
																<li>
																	<a href="title5.html">Title section 5</a>
																</li>
																<li>
																	<a href="title6.html">Title section 6</a>
																</li>
															</ul>
														</li>
														<li class="mega-menu-col">
															<a href="footer1.html#footer">Footers</a>
															<ul>
																<li>
																	<a href="footer1.html#footer">Footer Type 1</a>
																</li>
																<li>
																	<a href="footer2.html#footer">Footer Type 2</a>
																</li>
																<li>
																	<a href="footer3.html#footer">Footer Type 3</a>
																</li>
																<li>
																	<a href="footer4.html#footer">Footer Type 4</a>
																</li>
																<li>
																	<a href="footer5.html#footer">Footer Type 5</a>
																</li>
																<li>
																	<a href="footer6.html#footer">Footer Type 6</a>
																</li>
															</ul>
														</li>
														<li class="mega-menu-col">
															<a href="copyright1.html#copyright">Copyright</a>

															<ul>
																<li>
																	<a href="copyright1.html#copyright">Copyright 1</a>
																</li>
																<li>
																	<a href="copyright2.html#copyright">Copyright 2</a>
																</li>
																<li>
																	<a href="copyright3.html#copyright">Copyright 3</a>
																</li>
																<li>
																	<a href="copyright4.html#copyright">Copyright 4</a>
																</li>
																<li>
																	<a href="copyright5.html#copyright">Copyright 5</a>
																</li>
																<li>
																	<a href="copyright6.html#copyright">Copyright 6</a>
																</li>
															</ul>
														</li>

													</ul>
												</div> <!-- eof mega menu -->
											</li>
											<!-- eof pages -->


											<li>
												<a href="#">FÓRUM</a>
											</li>
											<!-- eof features -->


											<!-- blog -->
											<li>
												<a href="{% url 'blog:list' %}">BLOG</a>

											</li>
											<!-- eof blog -->


											<!-- shop -->
											<li>
												<a href="{% url 'core:loja-virtual' %}">LOJA MILICO</a>

											</li>
											<!-- eof shop -->


											<!-- contacts -->
											<li>
												<a href="{% url 'dashboard:index' %}">DASHBOARD</a>
											</li>
											<!-- eof contacts -->
										</ul>


									</nav>
									<!-- eof main nav -->

									<!--hidding includes on small devices. They are duplicated in topline-->
									<ul class="top-includes d-none d-xl-block">
										<li>
											<!--modal search-->
											<span>
												<a href="#" class="search_modal_button">
													<i class="fa fa-search"></i>
												</a>
											</span>

										</li>
										<li>
											<div class="dropdown">
												<a class="dropdown-toggle dropdown-shopping-cart" href="#" role="button" id="dropdown-shopping-cart" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
													<i class="ico icon-shopping-bag"></i>
													<span class="badge bg-maincolor">0</span>
												</a>
												<div class="dropdown-menu dropdown-menu-right ls" aria-labelledby="dropdown-shopping-cart">
													<div class="widget woocommerce widget_shopping_cart">


														<div class="widget_shopping_cart_content">

															<ul class="woocommerce-mini-cart cart_list product_list_widget ">
																<li class="woocommerce-mini-cart-item mini_cart_item">
																	<a href="#" class="remove" aria-label="Remove this item" data-product_id="73" data-product_sku="">×</a>
																	<a href="shop-product-right.html">
																		<img src="{% static 'images/shop/26.jpg' %}" alt="">Medical marijuana THC
																	</a>

																	<span class="quantity">1 ×
																		<span class="woocommerce-Price-amount amount">
																			<span class="woocommerce-Price-currencySymbol">$</span>
																			12.00
																		</span>
																	</span>
																</li>
																<li class="woocommerce-mini-cart-item mini_cart_item">
																	<a href="#" class="remove" aria-label="Remove this item" data-product_id="76" data-product_sku="">×</a>
																	<a href="shop-product-right.html">
																		<img src="{% static 'images/shop/26.jpg' %}" alt="">Medical marijuana THC
																	</a>

																	<span class="quantity">1 ×
																		<span class="woocommerce-Price-amount amount">
																			<span class="woocommerce-Price-currencySymbol">$</span>
																			15.00
																		</span>
																	</span>
																</li>
															</ul>

															<p class="woocommerce-mini-cart__total total">
																<strong>Subtotal:</strong>
																<span class="woocommerce-Price-amount amount">
																	<span class="woocommerce-Price-currencySymbol">$</span>
																	27.00
																</span>
															</p>

															<p class="woocommerce-mini-cart__buttons buttons">
																<a href="shop-cart.html" class="button wc-forward">View cart</a>
																<a href="shop-checkout.html" class="button checkout wc-forward ">Checkout</a>
															</p>
														</div>
													</div>

												</div>
											</div>
										</li>



				{% if user.is_authenticated %}
								{% include 'menu/menu_usuario.html' %}
					{%else%}
									<li>
										<span>
											<a class="phone_modal_button" href="#sign_in_modal"><span class="ico icon-male-user-shadow"></span></a>
										</span>

									</li>
					{% endif %}

									</ul>


								</div>
							</div>
						</div>
					</div>
					<!-- header toggler -->
					<span class="toggle_menu"><span></span></span>
				</header>

guiadomilico/templates/menu/menu-accounts.html
		<nav class="woocommerce-MyAccount-navigation">
											<ul>
												<li class="is-active">
													<a href="shop-account-dashboard.html">Minha conta</a>
												</li>
												<li>
													<a href="shop-account-downloads.html">Endereços</a>
												</li>
												<li>
													<a href="shop-account-downloads.html">Dados Bancários</a>
												</li>
												<li>
													<a href="shop-account-addresses.html">Segurança</a>
												</li>
												<li>
													<a href="shop-account-addresses.html">Preferências</a>
												</li>
												<li>
													<a href="{% url 'accounts:logout' %}">Sair</a>
												</li>
											</ul>
			</nav>

guiadomilico/templates/menu/menu_usuario.html
{% load static %}
			<li>

											<ul class="nav sf-menu my-menu">
												<li>
													<a href="#" ><img src="{% static 'images/avatar/police-8.png' %}" width="40" /></a>

												<ul style="display: none;">



													<li class="">

														<a href="#"><i class="fa fa-user-circle"></i>{{user.nome|title}}</a>

														<ul style="display: none; margin-top: 5px; left: -272px;">

															<li>
																<a href="{% url 'accounts:my-account' user.id %}"><i class="fa fa-user"></i> Meu dados</a>
															</li>
															<li>
																<a href="{% url 'accounts:my-account' user.id %}#tab02_pane"><i class="fa fa-home"></i> Endereços</a>
															</li>
															<li>
																<a href="#"><i class="fa fa-bank"></i> Dados Bancários</a>
															</li>
															<li>
																<a href="#"><i class="fa fa-cog"></i> Preferências</a>
															</li>
																<li>
																<a href="{% url 'accounts:logout' %}"><i class="fa fa-sign-out"></i> Sair</a>
															</li>

														</ul>
													</li>

													<li>
														<a href="#"><i class="fa fa-shopping-bag"></i>Pedidos</a>
													</li>

													<li>
														<a href="#"><i class="fa fa-ticket"></i>Meus cupons</a>
													</li>

													<li>
														<a href="shop-right.html"><i class="fa fa-heart"></i> Lista de desejos</a>
													</li>


												</ul>
												</li>
											</ul>


										</li>