guiadomilico/apps/accounts/urls.py
from django.conf.urls import url
from django.urls import path

from guiadomilico.apps.accounts.views import login, cadastro

app_name = 'accounts'

urlpatterns = [
    url(r'login/$', login.LoginView.as_view(), name='login'),
    url(r'logout/$', login.LoginView.as_view(), name='logout'),
    path('cadastro/', cadastro.CadastroWizard.as_view(), name='cadastroUsuario'),
    path('my-account/<int:pk>', cadastro.CadastroUpdateView.as_view(), name='my-account'),
    path('confirm/<str:uidb64>/<str:token>', cadastro.ativarCadastro, name='cadastroAtivar'),
    path('cadastro/ativar-conta', cadastro.EmailActiveView.as_view(), name='ativar-conta'),
    path('cadastro/reenviar-email', cadastro.accounts_inactive, name='cadastroReenvioEmail'),
    path('cadastro/ativado', cadastro.ativadoSucesso, name='ativado'),
    url('ajax/is_exists_register_ajax/', cadastro.is_exists_register_ajax, name='is_exists_register_ajax'),
    url('ajax/verifica_cep/', cadastro.consultar_cep, name='verifica_cep'),

]

guiadomilico/apps/base/urls.py
from django.conf.urls import url
from . import views


app_name = 'base'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^loja-virtual/$', views.ShopView.as_view(), name='loja-virtual'),

]

guiadomilico/apps/blog/urls.py
from django.conf.urls import url
from .views import base

app_name = 'blog'
urlpatterns = [
    url(r'^$', base.post_list, name='list'),
    url(r'^post/(?P<pk>[0-9]+)/$', base.post_detail, name='detail'),
    url(r'^post/new/$', base.post_new, name='post_new'),
    url(r'^post/(?P<pk>[0-9]+)/edit/$', base.post_edit, name='post_edit'),
]

guiadomilico/apps/dashboard/urls.py
from django.conf.urls import url
from . import views
from .views.views import DashboardView

app_name = 'dashboard'
urlpatterns = [
    url(r'^$', DashboardView.as_view(), name='index'),
    url(r'^posts$', views.views.post_list, name='posts'),
]

guiadomilico/urls.py
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url('admin/', admin.site.urls),
    #URL do app BASE:
    url(r'^', include('guiadomilico.apps.core.urls')),
    url(r'^accounts/', include('guiadomilico.apps.accounts.urls')),
    url(r'^dashboard/', include('guiadomilico.apps.dashboard.urls')),
    url(r'^blog/' , include('guiadomilico.apps.blog.urls')),
]

guiadomilico/apps/blog/forms/base.py
from django import forms

from guiadomilico.apps.blog.models import Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'text']

        labels = {
            'title':'Titulo da postagem',
            'text': 'Digite o conteúdo'
        }

        widgets = {
            'text': forms.Textarea(attrs={'hidden': 'hidden', '':'text'}),
        }

guiadomilico/apps/accounts/views/cadastro.py
from django.contrib.auth import logout, login

from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage, send_mail
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.urls import reverse_lazy, reverse
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views.generic import FormView, TemplateView
from guiadomilico.apps.accounts.forms import EnderecoFormSet, TelefoneFormSet
from guiadomilico.apps.accounts.token import account_activation_token
from guiadomilico.apps.accounts.forms.cadastro import CadastroUserForm, CadastroUpdateForm
from guiadomilico.apps.accounts.models.base import Usuario, Endereco
from formtools.wizard.views import SessionWizardView
from  django.views.generic.edit import UpdateView
from  django.views.generic.list import ListView

import pycep_correios as pycep

from ..models import *

def send_mail(request, usuario):
    current_site = get_current_site(request)
    mail_subject = "[Guia do Milico] Ativação de usuário necessária"
    message = render_to_string('accounts/email_ativacao.html', {
        'usuario': usuario,
        'dominio': current_site.domain,
        'uid': urlsafe_base64_encode(force_bytes(usuario.pk)),
        'token': account_activation_token.make_token(usuario),
    })
    to_email = usuario.email

    email = EmailMessage(
        mail_subject,
        message,
        to=[to_email]
    )

    email.send()


## VIEW EM DESENVOLVIMENTO ##
class CadastroUpdateView(UpdateView):
    template_name = 'accounts/my_account.html'
    model = Usuario
    form_class = CadastroUpdateForm
    context_object_name = "usuario"

    def get_success_url(self):
        id = self.kwargs.get(self.pk_url_kwarg)
        return reverse_lazy('accounts:my-account', kwargs={'pk': id })

    def get_context_data(self, **kwargs):
        id = self.kwargs.get(self.pk_url_kwarg)
        kwargs['usuario'] = Usuario.objects.filter(id=id).first()
        kwargs['usuario_form'] = CadastroUpdateForm(self.request.POST or None, instance=kwargs['usuario'])
        kwargs['endereco'] = list(Endereco.objects.filter(usuario_end__pk=self.kwargs['pk']).values())
        kwargs['TIPO_ENDERECO'] = TIPO_ENDERECO
        return super().get_context_data(**kwargs)



class CadastroListView(ListView):
    template_name = 'accounts/my_account.html'
    model = Usuario
    form_class = CadastroUserForm
    context_object_name = "usuario"


class EnderecoListView(ListView):
    template_name = 'accounts/my_account.html'
    model = Usuario
    form_class = CadastroUserForm
    context_object_name = "usuario"

class CadastroWizard(SessionWizardView):
    template_name = 'accounts/cadastro_usuario.html'

    FORMS = [("usuario", CadastroUserForm),
             ("endereco", EnderecoFormSet),
             ("telefone", TelefoneFormSet)
             ]

    form_list = FORMS


    def done(self, form_list, form_dict, **kwargs):

        template_name = 'accounts/email_notification.html'
        context = {}
        form_data = [form.cleaned_data for form in form_list]
        usuario = CadastroUserForm(form_data[0])
        user = usuario.save(commit=False)
        usuario.is_trusty = False
        instance = usuario.save()

        if 'endereco' in form_dict:
            formset = form_dict['endereco']
            if formset.is_valid():
                formset.instance = instance
                instance_endereco = formset.save()
                usuario.endereco_padrao = instance_endereco


        if 'telefone' in form_dict:
            formset = form_dict['telefone']
            if formset.is_valid():
                formset.instance = instance
                instance_telefone = formset.save()
                usuario.telefone_padrao = instance_telefone

        usuario.save()
        send_mail(self.request, user)

        # Context para avisar ao usuário que o cadastro foi efetuado com sucesso.
        # self.extra_context['form'] = self.get_form_instance(0)

        context['nomeCompleto'] = instance.get_full_name()
        context["emailEnvio"] = instance.email
        context["sucessoCadastro"] = "Um email foi enviado para {} com um link de ativação.".format(instance.email)

        return render(self.request, template_name, context )


'''
class CadastroUserView(FormView):
    form_class = CadastroUserForm
    template_name = 'accounts/cadastro_usuario.html'
    
    extra_context = {}
    endereco = EnderecoFormSet(prefix='endereco')
    telefone = TelefoneFormSet(prefix='telefone')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context["endereco"] = EnderecoFormSet(self.request.POST)
            context["telefone"] = TelefoneFormSet(self.request.POST)

        else:
            context["endereco"] = EnderecoFormSet()
            context["telefone"] = TelefoneFormSet()

        return context

    def get(self, request, *args, **kwargs):

        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        endereco = EnderecoFormSet()
        telefone = TelefoneFormSet()

        return self.render_to_response(
            self.get_context_data(form=form,
                                  endereco=endereco,
                                  telefone=telefone
                                  )
        )

    def post(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        endereco = EnderecoFormSet(self.request.POST)
        telefone = TelefoneFormSet(self.request.POST)

        if form.is_valid() and endereco.is_valid():
            return self.form_valid(form, endereco, telefone)
        else:
            return self.form_invalid(form, endereco, telefone)

    def form_valid(self, form, endereco, telefone):
        usuario = form.save(commit=False)
        usuario.is_trusty = False
        self.object = form.save()
        endereco.instance = self.object
        endereco.save()
        telefone.instance = self.object
        telefone.save()
        send_mail(self.request, usuario)

        # Context para avisar ao usuário que o cadastro foi efetuado com sucesso.
        self.extra_context['form'] = self.form_class

        self.extra_context['nomeCompleto'] = "{} {}".format(usuario.nome, usuario.sobrenome)
        self.request.session["emailEnvio"] = usuario.email
        self.request.session["sucessoCadastro"] = "Um email foi enviado para {} com um link de ativação.".format(
            usuario.email)

        return super(CadastroUserView, self).form_valid(form)

    def form_invalid(self, form, endereco, telefone):

        return self.render_to_response(
            self.get_context_data(form=form,
                                  endereco=endereco,
                                  telefone=telefone
                                  )
        )

'''


def ativadoSucesso(request):
    template_name = 'accounts/active_sucess.html'
    return render(request, template_name)


def ativa(uidb64, token):
    _return = {}
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = Usuario.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, Usuario.DoesNotExist):
        user = None

    if user is not None:
        if account_activation_token.check_token(user, token):
            user.is_trusty = True
            user.save()
        else:
            user = None
            _return['erro'] = 'Token inválido ou já utilizado!'
    else:
        _return['erro'] = 'Usuário inválido!'
    _return['usuario'] = user
    return _return


def ativarCadastro(request, uidb64, token):
    logout(request)

    _return = ativa(uidb64, token)
    if _return['usuario']:
        login(request, _return['usuario'])
        return redirect('accounts:ativado')
    else:
        context = {}
        context['erro'] = _return['erro']
        template_name = 'accounts/login.html'
        return render(request, template_name, context)


class EmailActiveView(TemplateView):
    template_name = 'accounts/email_notification.html'

    def get_context_data(self, **kwargs):
        context = super(EmailActiveView, self).get_context_data(**kwargs)
        context['sucessoCadastro'] = self.request.session["sucessoCadastro"]
        context['emailEnvio'] = self.request.session["emailEnvio"]
        del self.request.session["sucessoCadastro"]
        del self.request.session["emailEnvio"]

        return context


def accounts_inactive(request):
    logout(request)
    template_name = 'accounts/cadastro_inativo.html'
    context = {}

    if request.method == 'POST':
        username = request.POST['username']

        if Usuario.objects.filter(email=username).count() == 1:
            usuario = Usuario.objects.get(email=username)
        elif Usuario.objects.filter(username=username).count() == 1:
            usuario = Usuario.objects.get(username=username)
        else:
            usuario = None

        if usuario is not None:
            send_mail(request, usuario)

            request.session['sucessoCadastro'] = "Um email foi enviado para {} com um link de ativação.".format(
                usuario.email)
            request.session['emailEnvio'] = usuario.email

            return redirect(reverse('accounts:ativar-conta'))

        else:
            context['erro'] = "Nome de usuário/Email não encontrado!"

        return render(request, template_name, context)

    return render(request, template_name, context)


def is_exists_register_ajax(request):
    field = request.GET.get('field', None)
    validate = request.GET.get('validate', None)

    if validate is not None:
        if validate == 'username':

guiadomilico/apps/accounts/views/login.py
from django.contrib.auth import login, logout
from django.core.validators import validate_email

from django.utils.decorators import method_decorator
from django.urls import reverse_lazy

from django.views.decorators.csrf import csrf_protect
from django.views.decorators.cache import never_cache
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import FormView, RedirectView

from django.shortcuts import render

from guiadomilico.apps.accounts.models.base import Usuario
from guiadomilico.apps.accounts.forms.login import LoginForm


# Create your views here.

class LoginView(FormView):
    success_url = reverse_lazy('core:index')
    form_class = LoginForm
    template_name = 'accounts/login.html'

    @method_decorator(sensitive_post_parameters('password'))
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        request.session.set_test_cookie()
        logout(request)

        return super(LoginView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        login(self.request, form.get_user())

        if self.request.session.test_cookie_worked():
            self.request.session.delete_test_cookie()

        return super(LoginView, self).form_valid(form)

guiadomilico/apps/accounts/views/views.py
from django.contrib.auth import login, logout
from django.core.validators import validate_email

from django.utils.decorators import method_decorator
from django.urls import reverse_lazy

from django.views.decorators.csrf import csrf_protect
from django.views.decorators.cache import never_cache
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import FormView

from django.shortcuts import render

from guiadomilico.apps.accounts.models.base import Usuario
from guiadomilico.apps.accounts.forms.base import LoginForm

# Create your views here.

class LoginView(FormView):
	success_url = reverse_lazy('core:index')
	form_class = LoginForm
	template_name = 'accounts/login.html'

	@method_decorator(sensitive_post_parameters('password'))
	@method_decorator(csrf_protect)
	@method_decorator(never_cache)
	def dispatch(self, request, *args, **kwargs):
		request.session.set_test_cookie()
		logout(request)

		return super(LoginView, self).dispatch(request, *args, **kwargs)

	def form_valid(self, form):
		login(self.request, form.get_user())

		if self.request.session.test_cookie_worked():
			self.request.session.delete_test_cookie()

		return super(LoginView, self).form_valid(form)

guiadomilico/apps/blog/views/base.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from guiadomilico.apps.blog.forms import PostForm
from guiadomilico.apps.blog.models import Post


def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'blog/post_list.html', {'posts': posts})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})

def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blog:detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'dashboard/post_edit.html', {'form': form})


def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blog:detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'dashboard/post_edit.html', {'form': form})

guiadomilico/apps/core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


# Create your views here.

class ShopView(TemplateView):
    template_name = "core/shop.html"

    ## FALTA IMPLEMENTAR ##

class IndexView(TemplateView):
    template_name = "core/index.html"

    ## FALTA IMPLEMENTAR ##

class SucessView(TemplateView):
    template_name = "accounts/active_sucess.html"

    ## FALTA IMPLEMENTAR ##

guiadomilico/apps/dashboard/views/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.utils import timezone
from guiadomilico.apps.blog.models import Post


class DashboardView(TemplateView):
    template_name = "dashboard/index.html"


def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'dashboard/post_list.html', {'posts': posts})

guiadomilico/templates/dashboard/base.html
{% load static %}

{% block head %}
	{% include 'dashboard/head.html' %}
{% endblock %}

	<title>{%block title%} Dashboard - Guia do Milico{%endblock%}</title>






<div class="page-wrapper chiller-theme toggled">
  <a id="show-sidebar" class="btn btn-sm btn-dark" href="#">
    <i class="fas fa-bars"></i>
  </a>

  <nav id="sidebar" class="sidebar-wrapper">
    <div class="sidebar-content">
      <div class="sidebar-brand">
      <a class="link-logo" href="{% url 'core:index' %}">
                 <img src="{% static 'images/logo.png' %}" width="200px; class="logo" alt="">
</a>
        <div id="close-sidebar">
          <i class="fas fa-times"></i>
        </div>
      </div>

      <div class="sidebar-search">
        <div>
          <div class="input-group">
            <input type="text" class="form-control search-menu" placeholder="Pesquisar...">
            <div class="input-group-append">
              <span class="input-group-text">
                <i class="fa fa-search" aria-hidden="true"></i>
              </span>
            </div>
          </div>
        </div>
      </div>
      <!-- sidebar-search  -->
      <div class="sidebar-menu">
        <ul>
          <li class="header-menu">
            <span>Opções</span>
          </li>
          <li class="sidebar-dropdown">
            <a href="#">
              <i class="fa fa-book"></i>
              <span>Nosso Blog</span>
            </a>
            <div class="sidebar-submenu">
              <ul>
                <li>
                  <a href="{% url 'blog:post_new' %}">Nova publicação

                  </a>
                </li>
                <li>
                  <a href="{% url 'dashboard:posts' %}">Todas publicações</a>
                </li>
                <li>
                  <a href="#">Catregorias</a>
                </li>
              </ul>
            </div>
          </li>
          <li class="sidebar-dropdown">
            <a href="#">
              <i class="fa fa-shopping-cart"></i>
              <span>E-commerce</span>
            </a>
            <div class="sidebar-submenu">
              <ul>
                <li>
                  <a href="#">Products

                  </a>
                </li>
                <li>
                  <a href="#">Orders</a>
                </li>
                <li>
                  <a href="#">Credit cart</a>
                </li>
              </ul>
            </div>
          </li>
          <li class="sidebar-dropdown">
            <a href="#">
              <i class="far fa-gem"></i>
              <span>Components</span>
            </a>
            <div class="sidebar-submenu">
              <ul>
                <li>
                  <a href="#">General</a>
                </li>
                <li>
                  <a href="#">Panels</a>
                </li>
                <li>
                  <a href="#">Tables</a>
                </li>
                <li>
                  <a href="#">Icons</a>
                </li>
                <li>
                  <a href="#">Forms</a>
                </li>
              </ul>
            </div>
          </li>
          <li class="sidebar-dropdown">
            <a href="#">
              <i class="fa fa-chart-line"></i>
              <span>Charts</span>
            </a>
            <div class="sidebar-submenu">
              <ul>
                <li>
                  <a href="#">Pie chart</a>
                </li>
                <li>
                  <a href="#">Line chart</a>
                </li>
                <li>
                  <a href="#">Bar chart</a>
                </li>
                <li>
                  <a href="#">Histogram</a>
                </li>
              </ul>
            </div>
          </li>
          <li class="sidebar-dropdown">
            <a href="#">
              <i class="fa fa-globe"></i>
              <span>Maps</span>
            </a>
            <div class="sidebar-submenu">
              <ul>
                <li>
                  <a href="#">Google maps</a>
                </li>
                <li>
                  <a href="#">Open street map</a>
                </li>
              </ul>
            </div>
          </li>
          <li class="header-menu">
            <span>Extra</span>
          </li>
          <li>
            <a href="#">
              <i class="fa fa-book"></i>
              <span>Documentation</span>
            </a>
          </li>
          <li>
            <a href="#">
              <i class="fa fa-calendar"></i>
              <span>Calendar</span>
            </a>
          </li>
          <li>
            <a href="#">
              <i class="fa fa-folder"></i>
              <span>Examples</span>
            </a>
          </li>
        </ul>
      </div>
      <!-- sidebar-menu  -->
    </div>
    <!-- sidebar-content  -->
    <div class="sidebar-footer">
      <a href="#">
        <i class="fa fa-bell"></i>
        <span class="badge badge-pill badge-warning notification">3</span>
      </a>
      <a href="#">
        <i class="fa fa-envelope"></i>
        <span class="badge badge-pill badge-success notification">7</span>
      </a>
      <a href="#">
        <i class="fa fa-cog"></i>
        <span class="badge-sonar"></span>
      </a>
      <a href="#">
        <i class="fa fa-power-off"></i>
      </a>
    </div>
  </nav>

  {% block content %}

  {% endblock %}

</div>
<!-- page-wrapper -->


{% include 'dashboard/scripts.html' %}

guiadomilico/templates/dashboard/head.html
{% load static %}
{% block head %}
<head>
	<meta charset="utf-8">
	<!--[if IE]>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<![endif]-->
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon/favicon.ico' %}">
	<link rel="manifest" href="{% static 'images/favicon/site.webmanifest' %}">
	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
	<!-- Responsável por carregar os arquivos estáticos -->

	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css">
	<link rel="stylesheet" href="{% static 'css/dashboard_style.css' %}" class="color-switcher-link">
        <link rel="stylesheet" href="{% static 'css/icons.css' %}">
        <link rel="stylesheet" href="{% static 'css/editor.css' %}">

	<!--[if lt IE 9]>


	<![endif]-->

</head>

{% endblock %}

guiadomilico/templates/dashboard/index.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block title %}Seja bem vindo{{ block.super }}{% endblock %}
 {% block content %}

  <main class="page-content">
    <div class="container">
      <h2>Nova postagem</h2>
      <hr>
      <div class="row">
        <div class="form-group col-md-12">
          <p>This is a responsive sidebar template with dropdown menu based on bootstrap 4 framework.</p>
          <p> You can find the complete code on <a href="https://github.com/azouaoui-med/pro-sidebar-template" target="_blank">
              Github</a>, it contains more themes and background image option</p>
        </div>
        <div class="form-group col-md-12">
          <iframe src="https://ghbtns.com/github-btn.html?user=azouaoui-med&repo=pro-sidebar-template&type=star&count=true&size=small" frameborder="0" scrolling="0" width="90px" height="30px"></iframe>
          <iframe src="https://ghbtns.com/github-btn.html?user=azouaoui-med&repo=pro-sidebar-template&type=fork&count=true&size=small" frameborder="0" scrolling="0" width="90px" height="30px"></iframe>
        </div>
        <div class="form-group col-md-12">
          <div class="alert alert-success" role="alert">
            <h4 class="alert-heading">New !</h4>
            <p>New react pro sidebar library is now available on <a href="https://www.npmjs.com/package/react-pro-sidebar" target="_blank">npm</a> <a href="https://github.com/azouaoui-med/react-pro-sidebar" target="_blank">
                <img alt="GitHub stars" src="https://img.shields.io/github/stars/azouaoui-med/react-pro-sidebar?style=social" />
              </a></p>
            <a href="https://github.com/azouaoui-med/react-pro-sidebar" target="_blank" class="btn btn-sm btn-primary mr-2">
              Github</a>
            <a href="https://azouaoui-med.github.io/react-pro-sidebar" target="_blank" class="btn btn-sm btn-success">
              Demo</a>

          </div>

        </div>
      </div>

      <h5>More templates</h5>
      <hr>
      <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
          <div class="card rounded-0 p-0 shadow-sm">
            <img src="https://user-images.githubusercontent.com/25878302/58369568-a49b2480-7efc-11e9-9ca9-2be44afacda1.png" class="card-img-top rounded-0" alt="Angular pro sidebar">
            <div class="card-body text-center">
              <h6 class="card-title">Angular Pro Sidebar</h6>
              <a href="https://github.com/azouaoui-med/angular-pro-sidebar" target="_blank" class="btn btn-primary btn-sm">Github</a>
              <a href="https://azouaoui-med.github.io/angular-pro-sidebar/demo/" target="_blank" class="btn btn-success btn-sm">Demo</a>
              <hr>
              <a href="https://github.com/azouaoui-med/react-pro-sidebar" target="_blank">
                <img alt="GitHub stars" src="https://img.shields.io/github/stars/azouaoui-med/angular-pro-sidebar?style=social" />
              </a>
              <a href="https://github.com/azouaoui-med/react-pro-sidebar" target="_blank">
                <img alt="GitHub stars" src="https://img.shields.io/github/forks/azouaoui-med/angular-pro-sidebar?style=social" />
              </a>

            </div>

          </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
          <div class="card rounded-0 p-0 shadow-sm">
            <img src="https://user-images.githubusercontent.com/25878302/58369258-33f20900-7ef8-11e9-8ff3-b277cb7ed7b4.PNG" class="card-img-top rounded-0" alt="Angular pro sidebar">
            <div class="card-body text-center">
              <h6 class="card-title">Angular Dashboard</h6>
              <a href="https://github.com/azouaoui-med/lightning-admin-angular" target="_blank" class="btn btn-primary btn-sm">Github</a>
              <a href="https://azouaoui-med.github.io/lightning-admin-angular/demo/" target="_blank" class="btn btn-success btn-sm">Demo</a>
              <hr>
              <a href="https://github.com/azouaoui-med/react-pro-sidebar" target="_blank">
                <img alt="GitHub stars" src="https://img.shields.io/github/stars/azouaoui-med/lightning-admin-angular?style=social" />
              </a>
              <a href="https://github.com/azouaoui-med/react-pro-sidebar" target="_blank">
                <img alt="GitHub stars" src="https://img.shields.io/github/forks/azouaoui-med/lightning-admin-angular?style=social" />
              </a>
            </div>
          </div>
        </div>
      </div>
      <hr>

      <footer class="text-center">
        <div class="mb-2">
          <small>
            © 2020 made with <i class="fa fa-heart" style="color:red"></i> by - <a target="_blank" rel="noopener noreferrer" href="https://azouaoui.netlify.com">
              Mohamed Azouaoui
            </a>
          </small>
        </div>

        <div>
          <a href="https://github.com/azouaoui-med" target="_blank">
            <img alt="GitHub followers" src="https://img.shields.io/github/followers/azouaoui-med?label=github&style=social" />
          </a>
          <a href="https://twitter.com/azouaoui_med" target="_blank">
            <img alt="Twitter Follow" src="https://img.shields.io/twitter/follow/azouaoui_med?label=twitter&style=social" />
          </a>
        </div>
      </footer>

    </div>

  </main>

 {% endblock %}